// Generated by https://quicktype.io

import 'package:tour_guide/data/entities/Project.dart';
import 'package:tour_guide/data/entities/userVolunteer.dart';

class Application {
  String creationDate;
  int id;
  int status;
  UserVolunteer user;
  Project project;

  Application({
    this.creationDate,
    this.id,
    this.status,
    this.user,
    this.project,
  });
  Application.fromJson(Map jsontmp) {
    this.creationDate = jsontmp["creation_date"];
    this.id = jsontmp["id"];
    this.status = jsontmp["status"];
    this.user = UserVolunteer.fromJson(jsontmp["applicant"]);
    this.project = Project.fromJson(jsontmp["project"]);
  }
}
